### ISSUE TITLE
Settings do not properly disable install action "write to file"

### ISSUE THREAD

**Issue by carlgustavh** [dasorik/continuum-mod-manager#5]
Everything is in the zip:
[Modelviewer Maps 1.0.2.zip](https://github.com/dasorik/continuum-mod-manager/files/14823574/Modelviewer.Maps.1.0.2.zip)
___
If we just look at the following code:
(line 23-29 in config.json)
```json
			{
				"SettingID": "enable-modelviewer-black",
				"SettingName": "Enable blackscreen map",
				"Type": "Checkbox",
				"DefaultValue": true,
				"Description": "When enabled, this will enable the blackscreen map"
			},
```
(line 95-106 in config.json)
```json
		{
			"Action": "WriteToFile",
			"TargetFile": "[Game]\\assets\\gamedb\\core\\zonelist.lua",
			"Content": [
			  {
				"DataFilePath": "[Mod]\\modelviewer_blackscreen.txt",
				"StartOffset": 181847,
				"Replace": false,
				"Disabled": "$MOD.enable-modelviewer-black = false"
			  }
			]
		},
```
It would seem that this settings were set up properly. But regardless of that, if the checkbox is unchecked, the contents of modelviewer_blackscreen.txt are still appended to zonelist.lua at the correct startoffset.

**Comment by dasorik** [comment]
Hi @carlgustavh, this is not a bug. The 'Disabled' property applies only to the action itself, in this scenario you've added this to one of the entries under 'Content'. To disable the action you would need to do the following:

```json
{
    "Action": "WriteToFile",
    "TargetFile": "[Game]\\assets\\gamedb\\core\\zonelist.lua",
    "Content": [
        {
            "DataFilePath": "[Mod]\\modelviewer_blackscreen.txt",
            "StartOffset": 181847,
            "Replace": false
        }
    ],
    "Disabled": "$MOD.enable-modelviewer-black = false"
},
```

If you need to have certain content conditionally written based on a mix of settings or always included, you can use two or more 'WriteToFile' actions. See the example below where two actions have been added with different inclusion criteria:

```json
// This action will not be triggered if enable-modelviewer-black is disabled
{
    "Action": "WriteToFile",
    "TargetFile": "[Game]\\assets\\gamedb\\core\\zonelist.lua",
    "Content": [
        {
            "DataFilePath": "[Mod]\\test_file_1.txt",
            "StartOffset": 54321,
            "Replace": true
        }
    ],
    "Disabled": "$MOD.enable-modelviewer-black = false"
},
// This action will always be run
{
    "Action": "WriteToFile",
    "TargetFile": "[Game]\\assets\\gamedb\\core\\zonelist.lua",
    "Content": [
        {
            "DataFilePath": "[Mod]\\test_file_2.txt",
            "StartOffset": 12345,
            "Replace": false
        }
    ],
},
```

**Comment by carlgustavh** [comment]
Ahhh, apologies. I will read the documentation more carefully next time 👍
